### ISSUE TITLE
JPM Support?

### ISSUE THREAD

**Issue by Mte90** [victorporof/firefox-restartless-template#7]
I see that developer an extension is simple with JPM maybe a support for this tool in this boilerplate it would be better for newbies (like me).

**Comment by jaredly** [comment]
:+1:

it's a little unclear how this setup interacts with the `jpm`-style setup, which seems to be how all the tutorials run ([example](https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Modifying_Web_Pages_Based_on_URL))
